import PAGE_DATA from './PAGE_DATA';
import STATIC_PATHS from './STATIC_PATHS';
import MAIN_NAVIGATION from './MAIN_NAVIGATION';
import FOOTER_NAVIGATION from './FOOTER_NAVIGATION';

export { STATIC_PATHS, PAGE_DATA, MAIN_NAVIGATION, FOOTER_NAVIGATION };
